### ISSUE TITLE
Implement setting of Testframework

### ISSUE THREAD

**Issue by hofmannc** [hofmannc/MPDL-AutomatedTesting#10]
@aapetrova
- Implementation of the general setting of the (testsuite-)structure in Selenium and connection to other tools as discussed:
  Selenuim Webdriver - Jenkins - TestLink - Jmeter (load testcases still not defined - will be done Monday)
- Structure of the testcases should allow modularity: Definition of three modules which can be run seperately from each other. The modules are:
  Basic: -> Testcases as described in current Keyword usage table. Testfocus lies on testing the general workflow.
  Data driven: -> Testcases to check all entry possibility of data entry fields. Testfocus on submission fields. Still to be defined.
  Funcional: -> Testcases to check the detailed functionality going deeper as "Basic". Still to be defined.
- Relevant TestLink-Testcases please see table "Keyword Usage" - since the table is not completely defined -  if not specified in table "Keyword usage" or "Data table" please use always the simplest choice for the Testcases. If possible distribute some simple variety, e.g in the first Bibtex, second eScidoc etc. -> Please add this info in the excel table, so I can trace it.

--> I still have to rework the testcases for adding a file -> please distribute "public, privat and restricted" ramdomly over the testcases.

[160718_data table_PubMan_Selenium.xlsx](https://github.com/hofmannc/MPDL-AutomatedTesting/files/401857/160718_data.table_PubMan_Selenium.xlsx)

[160608_Keyword Usage_PubMan_Selenium.xlsx](https://github.com/hofmannc/MPDL-AutomatedTesting/files/401861/160608_Keyword.Usage_PubMan_Selenium.xlsx)

**Comment by aapetrova** [comment]
09.08: Test framework was implemented and the specified test cases were added. The code is uploaded on GitHub (https://github.com/MPDL/PubManAutomatedTesting) and integrated on Jenkins.

Initial TestLink thoughts: install the TestLink plugin on Jenkins, and for every test case upload .java file with the specific test. Since one Java test case consists of several TestLink test cases, it should be checked if the plugin supports a one-to-many relationship.

Tasks left: TestLink integration, improve extensibility of files (for data-driven testing)
